/**
 * Generated by tsnapi — public API snapshot of `@yunzhen/permission-expression`
 */
// #region Types
export type Authority = string | PermissionExpression;
export type ExpressionSyntaxErrorCode = 'EXPRESSION_TOO_DEEP' | 'EMPTY_EXPRESSION' | 'UNEXPECTED_END' | 'UNEXPECTED_TOKEN' | 'UNMATCHED_CLOSING_PARENTHESIS' | 'UNMATCHED_OPENING_PARENTHESIS';
export type PermissionExpression = {
  type: 'permission';
  name: string;
} | {
  type: 'not';
  expression: PermissionExpression;
} | {
  type: 'and' | 'or';
  left: PermissionExpression;
  right: PermissionExpression;
};
// #endregion

// #region Classes
export declare class ExpressionSyntaxError extends SyntaxError {
  readonly code: ExpressionSyntaxErrorCode;
  readonly position: number;
  constructor(_: ExpressionSyntaxErrorCode, _: number);
}
// #endregion

// #region Functions
export declare function compile(_: string): PermissionExpression;
export declare function hasPermission(_: Authority, _: ReadonlySet<string>): boolean;
export declare function stringify(_: PermissionExpression): string;
// #endregion